# Generated by Django 4.2.7 on 2023-12-06 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True)),
                ('created_date', models.DateTimeField()),
                ('changed_date', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('why_deleted', models.TextField(max_length=500, null=True)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_by', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
