# Generated by Django 4.2.7 on 2023-12-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
