# Generated by Django 4.2.7 on 2023-12-07 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source_type', '0001_initial'),
        ('address', '0001_initial'),
        ('lead_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True)),
                ('lelead_type_changed_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('changed_date', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('why_deleted', models.TextField(max_length=500, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_changer', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_creator', to=settings.AUTH_USER_MODEL)),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_deleter', to=settings.AUTH_USER_MODEL)),
                ('lead_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_type.leadtype')),
                ('source_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='source_type.sourcetype')),
            ],
        ),
    ]
